### ISSUE TITLE
Special handling on ranges for pre-release versions

### ISSUE THREAD

**Issue by sdboyer** [Masterminds/semver#10]
As mentioned in #7 , I want us to borrow another idea from dart's pub and create some special logic around how pre-release versions are interpreted with respect to ranges. This does involve breaking some math rules, but I think the benefit for users is considerable.

Here's the wording from [their README](https://github.com/dart-lang/pub_semver/blob/master/README.md), which really pretty much covers it:

> **Pre-release versions are excluded from most max ranges.** Let's say a
>     user is depending on "foo" with constraint `>=1.0.0 <2.0.0` and that "foo"
>     has published these versions:
> 
> ```
> *  `1.0.0`
> *  `1.1.0`
> *  `1.2.0`
> *  `2.0.0-alpha`
> *  `2.0.0-beta`
> *  `2.0.0`
> *  `2.1.0`
> ```
> 
>    Versions `2.0.0` and `2.1.0` are excluded by the constraint since neither
>     matches `<2.0.0`. However, since semver specifies that pre-release versions
>     are lower than the non-prerelease version (i.e. `2.0.0-beta < 2.0.0`, then
>     the `<2.0.0` constraint does technically allow those.
> 
>    But that's almost never what the user wants. If their package doesn't work
>     with foo `2.0.0`, it's certainly not likely to work with experimental,
>     unstable versions of `2.0.0`'s API, which is what pre-release versions
>     represent.
> 
>    To handle that, `<` version ranges don't allow pre-release versions of the
>     maximum unless the max is itself a pre-release, or the min is a pre-release
>     of the same version. In other words, a `<2.0.0` constraint will prohibit not
>     just `2.0.0` but any pre-release of `2.0.0`. However, `<2.0.0-beta` will
>     exclude `2.0.0-beta` but allow `2.0.0-alpha`. Likewise, `>2.0.0-alpha
>     <2.0.0` will exclude `2.0.0-alpha` but allow `2.0.0-beta`.

We don't have to follow their exact rules, necessarily, but the basic idea that `<2.0.0` does _not_ include, say, `2.0.0-alpha` is really important. Otherwise, people who've set totally normal constraints like `^1.1.0` will find upgraded to `2.0.0` pre-releases without warning - violating the spirit of the caret.

**Comment by sdboyer** [comment]
I can't remember if we've already discussed this elsewhere, but my thinking moved on from this several months ago. I'm now thinking it's better to just follow the pattern used at least by npm and cargo, and I think also composer - ranges should not allow prerelease versions, period.

**Comment by mattfarina** [comment]
@sdboyer what if a range includes pre-releases? For example, `>= 1.2.3-beta.1`

**Comment by sdboyer** [comment]
ugh, rawr.

looks like npm handles that by allowing prerelease versions _only_ in that same major, minor and patch series. that strikes me as reasonable. what do you think?

**Comment by mattfarina** [comment]
sounds good to me. Better than what the 1.x version does.

**Comment by sdboyer** [comment]
OK. It's a nontrivial refactor to support, but it's definitely gotta happen.

**Comment by sdboyer** [comment]
It actually wasn't that bad :)

**Comment by carolynvs** [comment]
I'm hoping you can help answer a question on how to test if a version within in a range. When the version that I am checking has a prerelease tag, the Constraint fails in an unexpected way, considering that LessThan works as expected.

```golang
func TestRange(t *testing.T) {
	c, _ := semver.NewConstraint("< 1.13.0-rc1")
	v, _ := semver.NewVersion("1.11.0-rc1")
	err := c.Matches(v)
	if err != nil {
		t.Fatal(err)
	}
}
// This fails with "1.11.0-rc1 has prerelease data, so is omitted by the range <1.13.0-rc1"

func TestLessThan(t *testing.T) {
	cutoff, _ := semver.NewVersion("1.13.0-rc1")
	v, _ := semver.NewVersion("1.11.0-rc1")
	if !v.LessThan(cutoff) {
		t.Fail()
	}
}
// This passes
```

Should I just not use Constraints and stick with LessThan? Strip the prerelease tag off before checking if it matches a constraint? Submit a PR? 😉 

For context, I am using this package in the Docker Version Manager, and need to do checks like "if the version being downloaded falls within this range, download the binary from this location".

**Comment by sdboyer** [comment]
on the 2.x branch, there's a big difference between a compatibility range and an ordinal range. range constraints in this lib are designed to model compatibility per the semver rules, which means that they can have some peculiar rules around whether e.g. prerelease versions are incorporated or not.

if you just want to know whether one version is less than another, then yeah, you're better off with the latter check.
