### ISSUE TITLE
Find best match given an input and an array

### ISSUE THREAD

**Issue by DominicTobias** [Masterminds/semver#100]
Hi thanks for this lib,

I was wondering if it's possible to use it to achieve this:

Given an array of possible versions, find the highest matching one. So e.g:

```
["1.2.3", "1.2.4", "1.3.0"]
```

so `~1.2.1` should match `1.2.4` and `^1.2.1` should match `1.3.0` (since caret allow minor version increments).

Is this possible with this lib? I couldn't see something obvious in the readme to help me do it so just checking.

**Comment by mattfarina** [comment]
@DominicTobias that's exactly what this lib does.

**Comment by mattfarina** [comment]
I'm going to close this support/question. If there are further questions please feel free to ask.
