### ISSUE TITLE
Be able to print out Constraints to string

### ISSUE THREAD

**Issue by alenkacz** [Masterminds/semver#101]
Right now, it's not possible for error messages etc. to print out the constraint itself. It would be good to have inverse function to `parseConstraint` and be able to get back the constraint as printable string.

**Comment by alenkacz** [comment]
@mattfarina if you agree with this feature I can contribute the solution to that

**Comment by mattfarina** [comment]
@alenkacz i like the idea. Go for it.

**Comment by mattfarina** [comment]
With the merger of #117 this is now available. It will be in the release of v3

**Comment by mattfarina** [comment]
Note, if someone wants to backport this to the v1 I would be open to it.
