### ISSUE TITLE
Stop using pointer receiver on *Version

### ISSUE THREAD

**Issue by sdboyer** [Masterminds/semver#11]
That we use a pointer receiver for `Version`'s methods has frustrated me for a while for two basic reasons:
- It meant doing a lot of nil-checking all over the API, rather than just being able to call methods that would respond normally. The `areEq()` func is just one place that I sorta shimmed around this:
  
  ``` go
  
  func areEq(v1, v2 *Version) bool {
    if v1 == nil && v2 == nil {
        return true
    }
  
    if v1 != nil && v2 != nil {
        return v1.Equal(v2)
    }
    return false
  }
  ```
- It also means that all the version objects we create (and therefore also, all the constraint objects we create) allocate and escape to the heap. (see output of `go test -gcflags -m`)

Both of these things annoyed me, but what really pushed me over the edge was working on `rangeConstraint`: I realized that I was effectively using a `nil` `min` or `max` as either 'zero' or 'infinity', respectively. Conflating two meanings into the same nil space is generally a bad idea, and had the effect of making it very hard to write any helper methods for computation on versions from ranges: I couldn't know if a nil meant a max or a min (or an unintentionally empty version).

So, this issue is to drop the pointer receiver. Doing so will mean a bit of refactoring to tighten things back up, but it'll be worth it.

We need to do this before a 2.0.0 release; it'll be a breaking API change, so we need to lump it in with everything from #7.

**Comment by sdboyer** [comment]
A slightly more detailed explanation of the performance issue:

With the way that [go's escape analysis](http://blog.rocana.com/golang-escape-analysis) works, creating and returning a pointer value from outside of the scope in which it was created will *always* result in a heap allocation. (Go's escape analysis is not very sophisticated right now). Avoiding small allocations are one of the first and major things you do to improve runtime performance - see, for example, [this ol' Cloudflare piece](https://blog.cloudflare.com/recycling-memory-buffers-in-go/).

Moreover, because of the typical use pattern for a version, you also get bit on GC. It's not uncommon - say, in [vsolver](https://github.com/sdboyer/vsolver) - to create lots of `*Version` instances, even just ephemeral ones as part of a larger calculation. (The 2.x branch of this lib does this internally as well, with the new constraint calculation system.) This means creating lots of typically short-lived, small (almost always <100 bytes, often only 24 bytes), heap-allocated values. All of those become extraneous garbage that the GC has to deal with.

And, really, this is an easy win, because there's no intrinsic need for versions to be heap allocated. They consistent entirely of stack-allocable components - three `int64`s, and three immutable `string`s. If people want to use this library as a component in a serious, larger, and especially long-lived application, it shouldn't make allocations it doesn't have to, or make a needless mess for GC to clean up.

**Comment by mattfarina** [comment]
@sdboyer thanks for providing the detail and those pointers (pun intended).

**Comment by mattfarina** [comment]
Closing because this has been merged.
