### ISSUE TITLE
constraintCaret broken

### ISSUE THREAD

**Issue by aaronbee** [Masterminds/semver#119]
Commit 6e10208dbd98598d9b573411da40bfd7fc0c2ef3 broke `constraintCaret`. If the major version is greater than constraint major version and if some combination of minor or patch versions are equal, the constraint falsely passes. The following test case added to `TestConstraintCheck` reproduces the behavior.
```
		{"^1.1.0", "2.1.0", false},
		{"^1.2.0", "2.2.1", false},
```
```
--- FAIL: TestConstraintCheck (0.00s)
    constraints_test.go:197: Constraint "^1.0.0" failing with "2.1.0"
    constraints_test.go:197: Constraint "^1.2.0" failing with "2.2.1"
```

**Comment by mattfarina** [comment]
I can confirm the bug and will have a fix out shortly. Thanks for reporting this.
