### ISSUE TITLE
Please flush out v3 Changelog

### ISSUE THREAD

**Issue by kevinburke** [Masterminds/semver#127]
Hi,
I'm trying to update golang/dep to use the latest version of this library but I've run into a few problems.

- Previously you could cast the result of `semver.NewConstraint` to a `semver.Version`. Now you can't. The CHANGELOG gives no guidance on how to update this.
- `semver.NewConstraintIC` seems to have disappeared and there's no guidance in the CHANGELOG on how to update it.

Confusingly, when I generate a diff of the version we're on vs. master, `NewConstraintIC` isn't even in it as being removed. So I'm not even sure where to get started. https://github.com/Masterminds/semver/compare/24642bd0573145a5ee04f9be773641695289be46...fe7c21038085e01e67044ec1efe3afb1eaa59f75

**Comment by kevinburke** [comment]
If you want to reproduce you can check out the build here. https://travis-ci.org/golang/dep/builds/588252088

**Comment by mattfarina** [comment]
For reference on my archiving comment see https://github.com/golang/go/issues/29639#issuecomment-454509924 where it says

> Once modules is moved out of experimental (we are targeting Go 1.13), we will likely archive the dep repo shortly after to avoid confusion on which dependency management solution the Go project officially supports. We will do our best to communicate when exactly the archive will happen to avoid surprise, but it should be planned for.
