### ISSUE TITLE
Constraints marshaller

### ISSUE THREAD

**Issue by aegershman** [Masterminds/semver#130]
disclaimer: I'm new to golang, might be doing something wrong or missing something in front of me

Could `Constraints` include a default json/yaml marshaller similar to https://github.com/Masterminds/semver/issues/44 so that `Constraints` could be used directly when unmarshalling into a struct without [writing a custom one](https://blog.gopheracademy.com/advent-2016/advanced-encoding-decoding/)?

Feel free to close whenever. Thanks for your time 👍

**Comment by SimonTheLeg** [comment]
just stumbled across this: Was there a specific reason this was closed? 

If not I would like to contribute to this. This functionality would be nice to have for my use-case and before I wrap the constraint type and implement a custom marshaller in my code, I think it makes more sense to contribute it upstream :)

**Comment by aegershman** [comment]
@SimonTheLeg the only reason I closed this was to trim my personal backlog of open issues. I'll re-open this, and please feel free to open a new issue where you're the original poster / or do whatever the maintainers prefer for issue management 👍

**Comment by aegershman** [comment]
Hi from the future! Closing to prune dead PRs
