### ISSUE TITLE
Improper Constrain error returned when no comma provided in range

### ISSUE THREAD

**Issue by giltohar** [Masterminds/semver#147]
I am returned this error: `"improper constraint: >=4.x.x <5.x.x"` when i don't provide a comma between the upper and lower bound. 

It works fine when comma is provided, but your docs say that comma or space are acceptable...

**Comment by mattfarina** [comment]
@giltohar which version of semver are you using? The lack of a comma was for v3. The previous version required a comma. I know this can be confusing.

**Comment by mrgadgil** [comment]
@mattfarina Which version of masterminds/semver should I use? I am looking for a which has fix and both , and space are accepted in the range

**Comment by mattfarina** [comment]
To support go modules, the space, and the comma you should use v3.

**Comment by mattfarina** [comment]
closing as this appears to be handled.
