### ISSUE TITLE
reading github.com/Masterminds/semver/go.mod at revision v1.12.2: unknown revision v1.12.2

### ISSUE THREAD

**Issue by Masquerade0097** [Masterminds/semver#152]
Getting the following error in go installs - 

`go: github.com/Masterminds/semver@v1.12.2: reading github.com/Masterminds/semver/go.mod at revision v1.12.2: unknown revision v1.12.2`

Go version - `1.13.10 `

I tried the removing the `Masterminds/semver` entries from go.sum, cleaning the cache `go clean -modcache` and `go get github.com/grpc-ecosystem/grpc-gateway`. But I get the same error again.
Is there any fix for this?

**Comment by mattfarina** [comment]
There is no semver v1.12.2. If you see the releases page you'll see https://github.com/Masterminds/semver/releases.
