### ISSUE TITLE
"3.0" should not match "<= 2.x"

### ISSUE THREAD

**Issue by derelk** [Masterminds/semver#16]
As discussed in Masterminds/glide#483, the tip of 2.x incorrectly indicates that `3.0` satisfies the constraint `<= 2.x`. This is a regression from all 1.x releases.

Sample code:

``` go
    c, _ := semver.NewConstraint("<= 2.x");
    v, _ := semver.NewVersion("3.0")
    fmt.Println(c.Matches(v))
```

outputs `<nil>`.

**Comment by sdboyer** [comment]
yeah, i remember feeling like something was fishy when i did this part of the impl, but i couldn't put my finger on it at the time. thanks!

**Comment by sdboyer** [comment]
(this should be closed)

**Comment by derelk** [comment]
Confirmed the fix against tip of 2.x.
