### ISSUE TITLE
match on build metadata

### ISSUE THREAD

**Issue by ltagliamonte-dd** [Masterminds/semver#164]
hello community!
Is there a way to match on semver build metadata?
I'm using build metadata to store the branch version and to avoid conflicts is 2 devs are working on the same chart.
I'm using helm cli that uses this library (v3) to find the correct version [link](https://github.com/helm/helm/blob/main/pkg/repo/index.go#L177) of a chart.
For example:
```
helm show chart --version '0.*.0+luigi-upgrade' repo/signadot
```
returns:
```
version: 0.3.0+chart-upgrade-c405a19a
```

instead of returning empty.
There is no chart with `+luigi-upgrade` build metadata.

**Comment by mattfarina** [comment]
Closing as this appears to be handled.
