### ISSUE TITLE
Convert ranges to tilde or carat form, if possible

### ISSUE THREAD

**Issue by sdboyer** [Masterminds/semver#18]
Right now, I'm staring at this diff:

``` diff
 - package: github.com/Masterminds/vcs
-  version: ^1.7.0
+  version: '>=1.7.0, <2.0.0'
 - package: github.com/codegangsta/cli
-  version: ~1.14.0
+  version: '>=1.14.0, <1.15.0'
```

We need to store the input to the constraint, and then return that back out on a `String()` call, as with `Version`s.

The problem there, of course, is when you start combining constraints - it's just no longer possible to respect the original exact user input. So, as soon as a programmatic combination occurs, we should probably just drop the original input, and recalculate it as needed on a `String()` call. When doing that, I think we should also then prefer to express ranges with carats and tildes, if it is correct to do so

**Comment by sdboyer** [comment]
heh. i was about to post an issue...till i saw i'd done it five months ago.

actually running into this now. will try to roll up a PR soon (against 2.x).

**Comment by mattfarina** [comment]
@sdboyer with the merge of the pull request do you see this as done?

**Comment by sdboyer** [comment]
ah yes sorry forgot to close
