### ISSUE TITLE
NewConstraint method faulty behavior

### ISSUE THREAD

**Issue by benjaminbear** [Masterminds/semver#185]
Used version: 3.1.1
When I try to create a constraint with NewConstraint method I get following returns:

**good Example**
c, cErr := semver.NewConstraint("12.3.4.1234")
c.String() = nil
cErr = "improper constraint: 12.3.4.1234"

**faulty behavior**
c, cErr := semver.NewConstraint("12.**23**.4.1234")
c.String() = "12.23.4 1234"
cErr = nil

or

c, cErr := semver.NewConstraint("12.3.**34**.1234")
c.String() = "12.3.34 1234"
cErr = nil

------------

I would expect the same behavior as with "12.3.4.1234", means telling me its not a contraint..

**Comment by benjaminbear** [comment]
FYI: the used regex to validate the contstraint fails: https://regex101.com/r/3fEGeK/1

**Comment by mattfarina** [comment]
I can explain what's going on here. `12.3.4.1234` is invalid because it has 4 parts and semver is only 3 parts.

`12.3.34 1234` is read as 2 separate constraints. `12.3.34` and `1234`. Those are added together. See https://github.com/Masterminds/semver#basic-comparisons

**Comment by benjaminbear** [comment]
Ah I'm sorry,  had to correct the 2 faulty examples.
Is this:
c, cErr := semver.NewConstraint("12.23.4.1234")
c.String() = "12.23.4 1234"
cErr = nil

expected behavior? Its a non semver string with 4 parts like in the first example, but handled differently. The third dot is removed and its a valid range?

**Comment by mattfarina** [comment]
I have verified the issue. https://go.dev/play/p/wMEsKXb5KEx

**Comment by mattfarina** [comment]
@benjaminbear The fix can be found in #186 and the commit message explains what happened to cause this.

I am planning on getting a new release out by the end of this week with some fixes and new functionality.

Feel free to double check my fix and tell me if it didn't work.

**Comment by benjaminbear** [comment]
Great to hear! Thank you very much @mattfarina
