### ISSUE TITLE
uint64s for 2.0?

### ISSUE THREAD

**Issue by sdboyer** [Masterminds/semver#19]
I'm kinda loathe to open this. Honestly, it sorta annoys me even just writing this. But right now, `Version` uses `int64` to represent the major, minor, and patch components of a version, which means negative numbers are allowed. The [spec's quite clear](http://semver.org/#spec-item-2) on this - these number must be nonnegative.

I get that using `uint64` can make some things more annoying, but it seems maybe worth it to switch over to using a type that matches the spec exactly, rather than leaving open the possibility of errors that we have to handle?

**Comment by mattfarina** [comment]
Closing because it was merged.
