### ISSUE TITLE
Feature: Version check that gives info about failures

### ISSUE THREAD

**Issue by technosophos** [Masterminds/semver#2]
It would be nice to have a variation of `Constraint.Check()` that could give information, on failure, about why it failed. I'm imagining something like this:

```
err := c.CheckError(myVer)
if err != nil {
    fmt.Printf("myVersion does not meet the requirements because: %s", err)
}
```

**Comment by mattfarina** [comment]
@technosophos I'm debating if the response should be an error, a slice of errors, an multiError (think `codegangsta/cli`), or a slice of strings. Any thoughts?

**Comment by mattfarina** [comment]
@technosophos can you please review PR #4 where I attempted to add a validator.

**Comment by technosophos** [comment]
This. Is. AWESOME!!!!

**Comment by mattfarina** [comment]
This has been merged and will be in the next release.
