### ISSUE TITLE
semver v3 regex is more inclusive than the official semver.org regex

### ISSUE THREAD

**Issue by oshirohugo** [Masterminds/semver#211]
The official Semantic Versioning website has a suggested [regex](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string).
Which is different from the one used in semver v3
https://github.com/Masterminds/semver/blob/master/version.go#L42
The results of applying them is different:
 This is the official one: https://regex101.com/r/Ly7O1x/3/
 This is the one from semver v3 applied to the same examples: https://regex101.com/r/LxcCgR/1
 
 Shouldn't they be the same?

**Comment by d0x7** [comment]
In my opinion, no, it should not be the same. As stated in the [README](https://github.com/Masterminds/semver#parsing-semantic-versions), there is a [StrictNewVersion](https://github.com/Masterminds/semver/blob/2f39fdc11c33c38e8b8b15b1f04334ba84e751f2/version.go#L68) and the more permissive [NewVersion](https://github.com/Masterminds/semver/blob/2f39fdc11c33c38e8b8b15b1f04334ba84e751f2/version.go#L158), which also allows things like v1 or v1.2 which are not strictly SemVer, but still ocurr often "in the wild".

In fact, I am very glad this library supports the more permissive one, as that's pretty much exactly what I need for a project. Now I only need to go from interval notations to this librarys format for comparing/validating versions and the more permissive NewVersion can handle the parsing and comparing :)

**Comment by oshirohugo** [comment]
Tks for your answer @d0x7 . Indeed `StrictNewVersion` is more restrictive, but still the following invalid versions are parsed without any errors:
```
1.1.2+.123
1.0.0-alpha..
1.0.0-alpha..1
1.0.0-alpha...1
1.0.0-alpha....1
1.0.0-alpha.....1
1.0.0-alpha......1
1.0.0-alpha.......1
```
[Simple tests](https://go.dev/play/p/WGA-0C1nYC6)
All of them are not valid according to the [official regex test](https://regex101.com/r/Ly7O1x/3/).
So, I believe at least `StrictNewVersion` should reject these cases

**Comment by mattfarina** [comment]
`StrictNewVersion` should definitely reject these cases.

`NewVersion` is loose but should still reject invalid versions. So, there are bugs in that, too.

**Comment by mattfarina** [comment]
`StrictNewVersion` should now handle the errors described in https://github.com/Masterminds/semver/issues/211#issuecomment-1638977007. It catches them.

`NewVersion` now catches the edge cases it shouldn't let though (e.g., `v1.2.3-.alpha`) while still being loose.

New tests were added to detect more. No existing tests were changed or removed.
