### ISSUE TITLE
Invalid semantic version for "7.0.12-1+deb.sury.org~xenial+1" version string

### ISSUE THREAD

**Issue by sidkshatriya** [Masterminds/semver#22]
`7.0.12-1+deb.sury.org~xenial+1` is a PHP version string.

```
semver.NewVersion("7.0.12-1+deb.sury.org~xenial+1")
```

I get Invalid Semantic Version error on Masterminds/semver.

**Comment by sidkshatriya** [comment]
Original Issue https://github.com/sidkshatriya/dontbug/issues/3

**Comment by sidkshatriya** [comment]
I have made a workaround so this bug is not blocking me anymore. So the main question is: Is this an expected or unexpected error from semver?

**Comment by sdboyer** [comment]
That's expected, sorry - `7.0.12-1+deb.sury.org~xenial+1` is not valid semver, according to [the spec](http://semver.org/).

**Comment by sidkshatriya** [comment]
Thanks for your reply. Closing ticket.
