### ISSUE TITLE
Ranges and pre-release bug

### ISSUE THREAD

**Issue by mattfarina** [Masterminds/semver#24]
Consider the case of a range `> 0` and the versions `0.0.1-beta` and `0`.

This range will return false for both. But, isn't `0.0.1-beta` greater that `0`? If a range like `> 0-a` is used than a version like `0` doesn't work. It's one of those edge cases when #21/#23 was fixed.

@technosophos this came about when I was trying to update helm for the latest release to deal with the pre-release issue.

Considering two options:

1. Handling this special edge case in the code.
2. Adding a flag to the constraints struct for `UsingPrerelease` to force it into place without putting a prerelease on the constraint.

@technosophos @sdboyer thoughts?

**Comment by technosophos** [comment]
Yeah, you're right. It does seem like any non-zero value should satisfy `> 0`.

**Comment by sdboyer** [comment]
This sort of thing is why I've imagined the implementation needs to have special values that represent the high (infinity) and low (zero) bounds.

**Comment by mattfarina** [comment]
PR on #25
