### ISSUE TITLE
constraint Parser Error

### ISSUE THREAD

**Issue by vdice** [Masterminds/semver#34]
I've encountered the following issue by way of specifying a 'pre-release' [Helm](https://github.com/kubernetes/helm) chart version dependency.

When specifying a chart version of, say, `v2.3.5-sha.20d586f`, it is happily parsed/constrained by this package and Helm is happy as well.

However, when adding a timestamp, resulting in a chart version of `v2.3.5-20161202202307-sha.e8fc5e5`, this package returns a `constraint Parser Error` from the following [logic](https://github.com/Masterminds/semver/blob/master/constraints.go#L188-L190).

In local testing, `semver.NewConstraint()` seems to allow up to 10 digits for the timestamp without throwing this particular error -- is there a semver rule that is being broken here in using >10 digits (14 to be precise)?  Or, might this be an addressable parsing issue in this package?

**Comment by mattfarina** [comment]
There is no rule about digit length. In this case the pre-release would be `20161202202307-sha.e8fc5e5`. I'll take a look at it on Monday.

**Comment by mattfarina** [comment]
A PR was started in #35

**Comment by mattfarina** [comment]
@vdice Can you take a look at #36? I think this will fix it.
