### ISSUE TITLE
add a cli

### ISSUE THREAD

**Issue by mh-cbon** [Masterminds/semver#43]
Hi,

Is it possible to consider to add a cmd folder with a cli program to manipulate a list of version coming from a pipe on the shell.

For example i run `$ git tag`, i get a long list of versions, i want only the last one, for that to happen correctly i need a program to read, parse,sort the lines as semver values.
```
0.0.35
0.0.36
0.0.37
0.0.38
0.0.39
0.0.4
0.0.5
0.0.6
0.0.7
0.0.8
0.0.9
1.0.0
```

Optionally, the program could receive range argument to filter the list.

For simple usage on all platform, it would be great to embed the capability to return only the oldest/newest version of the result list.

**Comment by mattfarina** [comment]
I'm up for a CLI. I'll review it soon.

**Comment by mattfarina** [comment]
There is now a cli called [vert](https://github.com/Masterminds/vert) that uses this library. @technosophos developed it awhile ago and we moved it over to the Masterminds org.
