### ISSUE TITLE
Asterisk and pre-release versions

### ISSUE THREAD

**Issue by sagikazarmark** [Masterminds/semver#48]
I would assume that `*` constraint just accepts any version that is `>=0.0.0`, but it does not accept eg. `3.0.0-rc2`.

Is this a bug or is it on purpose? (Can't recall at the moment how package managers behave in this scenario, but some of them also define a separate stability flag which modifies the behaviour of constraint checking, so in some cases the above example would work)

**Comment by mattfarina** [comment]
@sagikazarmark `*` accepts any release version. `3.0.0-rc2` is a pre-release version. This is similar to how others treat it. For example, node-semver (which powers npm)...

```sh
± semver -r "*" 1.2.3 1.2.3-alpha.1
1.2.3
```

Per the spec, pre-release versions may not be compatible with their releases. `*` is currently designed to work on releases. Does that help?

You should be able to use `>=0.0.0-1` and get everything including pre-releases. When a pre-release is included in the constraint they are then checked.

Does that help?

**Comment by sagikazarmark** [comment]
Yes, it does, thanks for the detailed clarification.
