### ISSUE TITLE
NewConstraint returns nil

### ISSUE THREAD

**Issue by nic-fio** [Masterminds/semver#63]
Hello, `semver.NewConstraint` returns err for `>= 1.3.1 < 2`

```go
c, err := semver.NewConstraint(">= 1.3.1 < 2")
```

**Comment by mattfarina** [comment]
@nic-fio multiple constraints needs to be separated by a comma as @ae-dg pointed out. Since this has been answered I'm going to close the issue. If you have any further needs please feel free to open a new issue or re-open this one.
