### ISSUE TITLE
Miscomparison of versions with "negative" pre-release identifiers

### ISSUE THREAD

**Issue by thrnio** [Masterminds/semver#74]
Consider `1.0.0-beta.-3`, `1.0.0-beta.-2`, and `1.0.0-beta.4`. Each of these is a valid SemVer version string. Per SemVer,

> Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order. Numeric identifiers always have lower precedence than non-numeric identifiers.

This means that `1.0.0-beta.4` should be treated as having a numeric second pre-release identifier, while `1.0.0-beta.-3` and `1.0.0-beta.-2` should be treated as having an ASCII alphanumeric second pre-release identifier. Therefore, the correct ordering of these versions should be:

~~~
1.0.0-beta.4 < 1.0.0-beta.-2 < 1.0.0-beta.-3
~~~

However, because the library parses the pre-release version identifiers `-2` and `-3` as numbers, it instead produces the reverse, incorrect ordering:

~~~
1.0.0-beta.-3 < 1.0.0-beta.-2 < 1.0.0-beta.4
~~~

**Comment by mattfarina** [comment]
This has been fixed on the release-1 and master branches. The fix will be in the upcoming releases.
