### ISSUE TITLE
NewVersion allows non-SemVer versions

### ISSUE THREAD

**Issue by thrnio** [Masterminds/semver#75]
The following versions are not valid SemVer, yet are parsed as valid by NewVersion:

* `1` – "A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers"
* `1.0` – "A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers"
* `01.01.01` – Major, minor, and patch versions "MUST NOT contain leading zeroes"
* `1.0.0-beta.02` – Regarding pre-release identifiers, "Numeric identifiers MUST NOT include leading zeroes."

**Comment by bmghirbi** [comment]
The PR #76 is fixes the first three use cases.
