### ISSUE TITLE
Pre-release versions handling not consistent

### ISSUE THREAD

**Issue by mtherreault** [Masterminds/semver#81]
In the documentation about pre-release version:

> In the order of precidence, pre-releases come before their associated releases. In this example 1.2.3-beta.1 < 1.2.3.

But code prove this claim to be not respected and behavior not consistent:

```
v, _ := semver.NewVersion("1.2.3-beta.1")

c1, _ := semver.NewConstraint("> 1.2.3")
c2, _ := semver.NewConstraint("< 1.2.3")

if ok, reasons := c1.Validate(v); !ok {
	for _, reason := range reasons {
		fmt.Println(reason)
	}
}

if ok, reasons := c2.Validate(v); !ok {
	for _, reason := range reasons {
		fmt.Println(reason)
	}
}
```
Will output:

```
1.2.3-beta.1 is less than or equal to 1.2.3
1.2.3-beta.1 is greater than or equal to 1.2.3
```

**Comment by mattfarina** [comment]
I've verified this is a bug. Thanks for catching it.

**Comment by EugenMayer** [comment]
was the main reason to not consider this library, switched to https://github.com/blang/semver right away - pitty was i discovered the bug myself instead of reading the issue queue before trying the lib ;/

Makes this library more or less useless (IMHO)

**Comment by mattfarina** [comment]
I'm working on this now. The bug has to do with the Validate messages and not the validation checks itself. If `Check` is used it behaves as expected. My guess would be that `Validate` has not been used very often with these conditions.
