### ISSUE TITLE
ValidPrerelease should end in $

### ISSUE THREAD

**Issue by jeremycarroll** [Masterminds/semver#86]
I was reading the code and came across:
```
const ValidPrerelease string = `^([0-9A-Za-z\-]+(\.[0-9A-Za-z\-]+)*)`
```
in `version.go`. I don't know go, but it seems to me to mis-implement the [metadata extension](https://semver.org/#spec-item-10), in that this regex matches '0==='
i.e.
```
	matched, err := regexp.MatchString(`^([0-9A-Za-z\-]+(\.[0-9A-Za-z\-]+)*)`, "0===")
```
gives true, nil.

**Comment by mattfarina** [comment]
Closing as this was merged.
