### ISSUE TITLE
Invalid constraint comparison for <11

### ISSUE THREAD

**Issue by jmorrell** [Masterminds/semver#93]
I would expect the following to both fail the constraint check here, but `< 11` is being interpreted differently

```go
c := "< 11.0"
d := "< 11"

withDot, _ := semver.NewConstraint(c)
noDot, _ := semver.NewConstraint(d)

version, _ := semver.NewVersion("11.1.0")

fmt.Println(withDot.Check(version)) // false
fmt.Println(noDot.Check(version))   // true
```

Namely `< 11` is hitting [this branch](https://github.com/Masterminds/semver/blob/master/constraints.go#L178) and being marked as `dirty` where as `< 11.0` does not

**Comment by jmorrell** [comment]
More succinctly `< 11` gets interpreted as `< 11.x` which seems like a potential bug. This comes from trying to migrate a service from Node to Go, and this is a case where the behavior here does not match [the behavior of the npm semver module](https://www.npmjs.com/package/semver).

**Comment by mattfarina** [comment]
@jmorrell Thanks. I'll take a look into this.

All of this would be so much easier if there was a semver range spec we could all follow.

**Comment by mattfarina** [comment]
A quick check of the node semver package...

```js
const semver = require('semver')
 
console.log(semver.satisfies('10.0.0', '<11')) // true
console.log(semver.satisfies('11.1.1', '<11')) // false
```

**Comment by mattfarina** [comment]
@jmorrell Thanks for bringing this to my attention. It would be far more intuitive to follow the flow of the node semver module. But, I think changing what we have now to follow node would break the major semver so we'd need to increment to a v2. Before I work to make changes I'm going to chase this down.

That being said, now is a good time for a v2 as a big project I work on is working on a major release so it can handle the breaking changes, too. This is a fitting time to deal with a v2.

**Comment by mattfarina** [comment]
This has now been fixed in the 3.x development branch and will be in the next release. Thanks for the feedback.

**Comment by mattfarina** [comment]
One quick note.. the nodejs semver package does one thing in its range syntax that is not semver. The point is noted in their docs at...

> For example, the range >1.2.3-alpha.3 would be allowed to match the version 1.2.3-alpha.7, but it would not be satisfied by 3.4.5-alpha.9, even though 3.4.5-alpha.9 is technically "greater than" 1.2.3-alpha.3 according to the SemVer sort rules. The version range only accepts prerelease tags on the 1.2.3 version. The version 3.4.5 would satisfy the range, because it does not have a prerelease flag, and 3.4.5 is greater than 1.2.3-alpha.7.

When sorting for semver they don't show everything that matches on prereleases if they strictly followed the semver sorting rules.

This semver package does not follow nodejs on this one point. There are use cases where people want the strict semver sorting when prereleases happen.
