### ISSUE TITLE
Lack of support for ranges without commas

### ISSUE THREAD

**Issue by jmorrell** [Masterminds/semver#95]
Another issue trying to replace a service using the [Node semver module](https://www.npmjs.com/package/semver) with this library comes from ranges defined without commas. Example: `>=1.2.9 <2.0.0`

This will only parse that range if it is expressed with a comma separator: `>=1.2.9, <2.0.0`

I was able to write a function that detects this case and rewrites the ranges to match: https://github.com/heroku/heroku-buildpack-nodejs/pull/657/files#diff-a1f7727d2be8b8d167a4562b0699702aR331 but wanted to file an issue in case this is a case you would like to support.

```go
// regex matching the semver version definitions
// Ex:
//    v1.0.0
//    9
//    8.x
const cvRegex string = `v?([0-9|x|X|\*]+)(\.[0-9|x|X|\*]+)?(\.[0-9|x|X|\*]+)?` +
	`(-([0-9A-Za-z\-]+(\.[0-9A-Za-z\-]+)*))?` +
	`(\+([0-9A-Za-z\-]+(\.[0-9A-Za-z\-]+)*))?`

 // regex matching the semver operators
const ops string = `=<|~>|!=|>|<|>=|=>|<=|\^|=|~`

 // Masterminds/semver does not support constraints like: `>1 <2`, preferring
// `>1, <2` with a comma separator. This catches this particular case and
// rewrites it
func rewriteRange(c string) string {
	constraintRangeRegex := regexp.MustCompile(fmt.Sprintf(
		`^\s*(%s)(\s*%s)\s*(%s)(\s*%s)$`,
		ops, cvRegex, ops, cvRegex,
	))

 	ors := strings.Split(c, "||")
	out := make([]string, len(ors))

 	for i, v := range ors {
		m := constraintRangeRegex.FindStringSubmatch(v)
		if m != nil {
			out[i] = fmt.Sprintf("%s%s, %s%s", m[1], m[2], m[12], m[13])
		} else {
			out[i] = v
		}
	}

 	return strings.Join(out, `||`)
}
```

**Comment by mattfarina** [comment]
@jmorrell Thanks for this work. I like this change. Will look for a place to bake it into the project.

**Comment by mattfarina** [comment]
#116 will add this feature

**Comment by mattfarina** [comment]
Closing as it's merged. Will be in the 3.0.0 release
